### ISSUE TITLE
Function 'sys_errlist' not found by require 'ffi/libc' on glibc 2.32

### ISSUE THREAD

**Issue by junaruga** [postmodern/ffi-libc#6]
Hello,

I got the following error "Function 'sys_errlist' not found" on my Linux distribution Fedora 34 environment.
Do you have any idea to fix it?
Thank you.

```
$ cat /etc/fedora-release 
Fedora release 34 (Rawhide)

$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC) 

$ rpm -q glibc
glibc-2.32.9000-17.fc34.x86_64

$ rpm -q glibc-devel
glibc-devel-2.32.9000-17.fc34.x86_64
```

`ffi-libc` is the latest version 0.1.0.

```
$ gem list ffi     

*** LOCAL GEMS ***

ffi (1.12.1)
ffi-libc (0.1.0)
```

```
$ ruby -e "require 'ffi/libc'"
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- ffi/libc (LoadError)
	10: from -e:1:in `<main>'
	 9: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:147:in `require'
	 8: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
	 7: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:159:in `require'
	 6: from /builddir/.gem/ruby/gems/ffi-libc-0.1.0/lib/ffi/libc.rb:13:in `<top (required)>'
	 5: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	 4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /builddir/.gem/ruby/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:9:in `<top (required)>'
	 2: from /builddir/.gem/ruby/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:10:in `<module:FFI>'
	 1: from /builddir/.gem/ruby/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:19:in `<module:LibC>'
/usr/share/gems/gems/ffi-1.12.1/lib/ffi/library.rb:342:in `attach_variable': Function 'sys_errlist' not found in [#<FFI::DynamicLibrary:0x0000556ea6f649c8>] (FFI::NotFoundError)
```

Perhaps, the `sys_errlist` does not exist on the new glibc version?
I find this article.
https://stackoverflow.com/questions/33948508/why-is-sys-errlist-deprecated-in-glibc

**Comment by junaruga** [comment]
This issue also happens on Fedora 33 (= the Fedora latest stable version).

```
$ cat /etc/fedora-release 
Fedora release 33 (Thirty Three)

$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

$ gcc --version
gcc (GCC) 10.2.1 20201016 (Red Hat 10.2.1-6)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ rpm -q glibc glibc-devel
glibc-2.32-1.fc33.x86_64
glibc-devel-2.32-1.fc33.x86_64

$ gem list ffi

*** LOCAL GEMS ***

ffi (1.13.1)
ffi-libc (0.1.0)

$ ruby -e "require 'ffi/libc'"
/home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:16: warning: already initialized constant FFI::LibC::NULL
/home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:16: warning: previous definition of NULL was here
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ffi/libc (LoadError)
	10: from -e:1:in `<main>'
	 9: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	 8: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	 7: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	 6: from /home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc.rb:13:in `<top (required)>'
	 5: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 4: from /usr/local/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:9:in `<top (required)>'
	 2: from /home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:10:in `<module:FFI>'
	 1: from /home/jaruga/.gem/ruby/2.7.0/gems/ffi-libc-0.1.0/lib/ffi/libc/libc.rb:19:in `<module:LibC>'
/home/jaruga/.gem/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:342:in `attach_variable': Function 'sys_errlist' not found in [#<FFI::DynamicLibrary:0x00000000015a1af8>] (FFI::NotFoundError)
```

If you want to test on the environment casually, you can use the docker containers here.
https://hub.docker.com/_/fedora/

**Comment by junaruga** [comment]
According to the official web [1] glibc 2.32 release note [2], here is the related document.

```
...
* The functions strerrorname_np and strerrordesc_np have been added.  The
  strerroname_np returns error number name (e.g. "EINVAL" for EINVAL) while
  strerrordesc_np returns string describing error number
  (e.g "Invalid argument" for EINVAL).  Different than strerror,
  strerrordesc_np does not attempt to translate the return description, both
  functions return NULL for an invalid error number.

  They should be used instead of sys_errlist and sys_nerr, both are
  thread and async-signal safe.  These functions are GNU extensions.
...
* The deprecated symbols sys_errlist, _sys_errlist, sys_nerr, and _sys_nerr
  are no longer available to newly linked binaries, and their declarations
  have been removed from from <stdio.h>.  They are exported solely as
  compatibility symbols to support old binaries.  All programs should use
  strerror or strerror_r instead.
...
```

The `sys_errlist` and `sys_nerr` in the following lines can be called conditionally or can be replaced to `strerrorname_np` and `strerrordesc_np`.

https://github.com/postmodern/ffi-libc/blob/d54876294f668ad3ca270a6f0c9bc4d97d0e5195/lib/ffi/libc/libc.rb#L19-L20


* [1] http://www.gnu.org/software/libc/
* [2] https://sourceware.org/pipermail/libc-announce/2020/000029.html

**Comment by lyiriyah** [comment]
@postmodern Can you comment on this? This is a pretty big bug.

**Comment by postmodern** [comment]
Wow, how did I miss this issue. I have removed them and will release a new version ASAP.

**Comment by lyiriyah** [comment]
@postmodern Thanks for that, it works now.
